package model;

import java.io.File;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;

import utils.CRegWrapper;

public class PTreeNode {
	// We should have a way to refer to the context in the tree and at the same
	// time, of course, the parent node.
	private ProbablityTree contextTree; 
	private PTreeNode parentNode; 
	
	private String nodeName = "PTreeNode"; // Specify the name of the node
	private HashSet<String> labelAtNode; // This set stores the label we care about at this Node
	private HashMap<String, Double> proTable; // This is the probability table for each label
	private LinkedList<PTreeNode> children; // This is the children of this node

	// A set of files where the related data from, some of the files should be
	// generated by the parent node
	private File trainFeatFile;
	private File trainRepFile;
	private File weightsFile;
	private File pridictFile;
	private File testFeatFile;
	
	
	public void train(){
		CRegWrapper.train(trainFeatFile, trainRepFile, weightsFile, "--l1 1.0");
	}
	
	public void predict(){
		CRegWrapper.predict(weightsFile, testFeatFile, pridictFile);
	}
	
	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
